"""Generate docs/FEATURES.md from the registry and the materialized store."""

from __future__ import annotations

from typing import Any, cast

import pandas as pd

from nvquant.features.store import FeatureStore


def render_feature_docs(store: FeatureStore) -> str:
    """Markdown table of every feature with lookback, lag, and summary statistics."""
    f = store.features.dropna()
    stats = pd.DataFrame({"mean": f.mean(), "std": f.std(), "min": f.min(), "max": f.max()})
    meta = store.metadata.set_index("column")
    lines = [
        "# Features",
        "",
        "Generated by `make features` from `nvquant.features.registry` and the feature store. Don't edit by hand.",
        "",
        f"- Rows: {store.info['n_rows']} sessions from {store.info['modeling_start']} to {store.info['end']}"
        f" (first complete row {store.info['first_complete_row']})",
        f"- Columns: {store.info['n_features']}",
        f"- Data hash `{store.info['data_hash']}`, config hash `{store.info['config_hash']}`",
        "",
        "Lag is in sessions and is applied on top of the function's own trailing window.",
        "Exogenous inputs (anything other than the target's own OHLCV) get a one-session lag.",
        "`known ahead` marks scheduled inputs (earnings dates are public about 20 sessions ahead).",
        "",
    ]
    for group, rows in meta.groupby("group", sort=False):
        lines += [f"## {group}", "", "| column | lookback | lag | known ahead | mean | std | min | max | description |",
                  "|---|---|---|---|---|---|---|---|---|"]  # fmt: skip
        for col, r in rows.iterrows():
            s = stats.loc[str(col)] if col in stats.index else None
            vals = (
                "| | | | "
                if s is None
                else f"{s['mean']:.4g} | {s['std']:.4g} | {s['min']:.4g} | {s['max']:.4g} "
            )
            lines.append(
                f"| `{col}` | {r['lookback']} | {r['lag']} | {r['known_ahead']} | {vals}| {r['description']} |"
            )
        lines.append("")
    records = cast(list[dict[str, Any]], store.info["fit_records"])
    d_values = sorted({rec["summary"]["d"] for rec in records if rec["feature"] == "fracdiff"})
    lines += [
        "## Fitted-feature refits",
        "",
        f"Fracdiff `d` chosen across refits: {', '.join(f'{d:g}' for d in d_values)}.",
        "",
    ]
    return "\n".join(lines)
